org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=simple_death_improvements
mod.name=Simple Death Improvements
mod.group=me.pajic
mod.version=1.5.1
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Less frustrating deaths - no item despawn, no item splatter, item safeguards and more
mod.sources_url=https://github.com/pajicadvance/simple-death-improvements
mod.homepage_url=https://modrinth.com/mod/simple-death-improvements
mod.issues_url=https://github.com/pajicadvance/simple-death-improvements/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

publish.modrinth=2JFsuD70
publish.curseforge=1163907
publish.github=false
